module.exports = {
  AUTH_TOKEN_TYPE: 'bearer',
  GRANT_TYPES: {
    PASSWORD: 'password',
    REFRESH_TOKEN: 'refresh_token',
  },
  ERROR_CODES: {
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    INVALID_FIELD_VALUE: 'INVALID_FIELD_VALUE',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    REQUEST_FAILED: 'REQUEST_FAILED',
    USER: {
      READ_FAILED: 'USER_READ_FAILED',
      NOT_FOUND: 'USER_NOT_FOUND',
      INACTIVE: 'USER_INACTIVE',
      EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
      INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    },
  },
};
